# Site settings
title: dgms code
email: dgmstuart@gmail.com
description: >
  This is the dev blog of Duncan Graeme MacDonald Stuart - a Technical
  Architect living in London. The focus is mostly Ruby on Rails
  with a little WordPress
url: "http://dgmstuart.github.io"

date_format: "%-d %b, %Y"
animated: false
ajaxify_contact_form: false

twitter_username: dgmstuart
github_username:  dgmstuart
disqus_shortname: dgmscode
stackoverflow_id: 1035431/dgmstuart
linkedin_username: duncangmstuart

google_analytics_code: UA-44436648-5

# Octopress 2-style permalink:
permalink: /blog/:year/:month/:day/:title/

jekyll-archives:
  enabled:
    - tags
    - categories
  layouts:
    tag: tag-archive
    category: category-archive

collections:
  conference-notes:
    output: true

# Build settings
markdown: kramdown
paginate: 10
sass:
  compressed: true
gems:
  - jekyll-paginate
  - jekyll-sitemap

exclude: ['LICENSE.txt', 'Gemfile.lock', 'Gemfile']

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  contact:
    email:    'Email Address'
    content:  'What would you like to say?'
    subject:  'New message from blog'
    submit:   'Say Hello'
    ajax:
      sending:  'sending..'
      sent:     'Message sent!'
      error:    'Error!'
  thanks: "Thanks for getting in touch. I'll reply as soon as possible."
